# Generated by Django 2.1.5 on 2019-02-03 01:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=246)),
                ('date_time', models.DateField()),
                ('num_passengers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('type', models.CharField(choices=[('1', 'Type1'), ('2', 'Type2'), ('3', 'Type3'), ('4', 'Does not matter')], default='4', max_length=1)),
                ('special_requests', models.CharField(max_length=300)),
                ('status_confirm', models.BooleanField(default=False)),
                ('status_conplete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
