# Generated by Django 2.1.5 on 2019-02-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideRequest', '0003_requestride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestride',
            name='driver',
        ),
        migrations.AddField(
            model_name='requestride',
            name='driver_name',
            field=models.CharField(max_length=246, null=True),
        ),
        migrations.AddField(
            model_name='requestride',
            name='driver_vehicle_type',
            field=models.CharField(max_length=246, null=True),
        ),
    ]
