# Generated by Django 2.1.5 on 2019-02-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideRequest', '0005_auto_20190203_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestride',
            old_name='remmaining_seat',
            new_name='remaining_seat',
        ),
    ]
