# Generated by Django 2.1.5 on 2019-02-06 16:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideRequest', '0006_auto_20190203_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestride',
            name='join_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=246), null=True, size=4),
        ),
    ]
