# Generated by Django 2.1.5 on 2019-02-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('type', models.CharField(choices=[('1', 'Type1'), ('2', 'Type2'), ('3', 'Type3')], max_length=1)),
                ('license_plate_num', models.CharField(max_length=264)),
                ('max_num_passengers', models.IntegerField()),
            ],
        ),
    ]
