# Generated by Django 2.1.5 on 2019-02-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverRegister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
